apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe-frontend-service
spec:
  type: NodePort # Or NodePort
  selector:
    app: tictactoe-backend
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 5000